/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    BaseChatList: typeof import('./src/components/chat/BaseChatList.vue')['default']
    BaseModal: typeof import('./src/components/modal/BaseModal.vue')['default']
    BaseNavigator: typeof import('./src/components/navigator/BaseNavigator.vue')['default']
    BasePageLayout: typeof import('./src/components/layout/BasePageLayout.vue')['default']
    ChatRoomContent: typeof import('./src/components/chat/ChatRoomContent.vue')['default']
    ChatRoomContentBody: typeof import('./src/components/chat/ChatRoomContentBody.vue')['default']
    ChatRoomContentBodyBar: typeof import('./src/components/chat/ChatRoomContentBodyBar.vue')['default']
    ChatRoomContentBodyMessage: typeof import('./src/components/chat/ChatRoomContentBodyMessage.vue')['default']
    ChatRoomContentFooter: typeof import('./src/components/chat/ChatRoomContentFooter.vue')['default']
    ChatRoomContentHead: typeof import('./src/components/chat/ChatRoomContentHead.vue')['default']
    ChatRoomFooterInput: typeof import('./src/components/chat/ChatRoomFooterInput.vue')['default']
    ChatRoomFooterToolBar: typeof import('./src/components/chat/ChatRoomFooterToolBar.vue')['default']
    ChatRoomList: typeof import('./src/components/chat/ChatRoomList.vue')['default']
    ChatRoomListItem: typeof import('./src/components/chat/ChatRoomListItem.vue')['default']
    ChatRoomListSearchBar: typeof import('./src/components/chat/ChatRoomListSearchBar.vue')['default']
    ChatRoomToolList: typeof import('./src/components/chat/ChatRoomToolList.vue')['default']
    Navigator: typeof import('./src/components/navigator/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/navigator/SearchBar.vue')['default']
    ThemeToggle: typeof import('./src/components/navigator/ThemeToggle.vue')['default']
    ToolBar: typeof import('./src/components/navigator/ToolBar.vue')['default']
    UserInfoModal: typeof import('./src/components/modal/UserInfoModal.vue')['default']
    VerticalLayout: typeof import('./src/components/layout/VerticalLayout.vue')['default']
  }
}
