/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseChatList: typeof import('./src/components/chat/BaseChatList.vue')['default']
    BaseModal: typeof import('./src/components/modal/BaseModal.vue')['default']
    BaseNavigator: typeof import('./src/components/navigator/BaseNavigator.vue')['default']
    BasePageLayout: typeof import('./src/components/layout/BasePageLayout.vue')['default']
    ChatRoomContent: typeof import('./src/components/chat/ChatRoomContent.vue')['default']
    ChatRoomContentBody: typeof import('./src/components/chat/ChatRoomContentBody.vue')['default']
    ChatRoomContentBodyBar: typeof import('./src/components/chat/ChatRoomContentBodyBar.vue')['default']
    ChatRoomContentBodyMessage: typeof import('./src/components/chat/ChatRoomContentBodyMessage.vue')['default']
    ChatRoomContentFooter: typeof import('./src/components/chat/ChatRoomContentFooter.vue')['default']
    ChatRoomContentHead: typeof import('./src/components/chat/ChatRoomContentHead.vue')['default']
    ChatRoomFooterInput: typeof import('./src/components/chat/ChatRoomFooterInput.vue')['default']
    ChatRoomFooterToolBar: typeof import('./src/components/chat/ChatRoomFooterToolBar.vue')['default']
    ChatRoomList: typeof import('./src/components/chat/ChatRoomList.vue')['default']
    ChatRoomListItem: typeof import('./src/components/chat/ChatRoomListItem.vue')['default']
    ChatRoomListSearchBar: typeof import('./src/components/chat/ChatRoomListSearchBar.vue')['default']
    ChatRoomToolList: typeof import('./src/components/chat/ChatRoomToolList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ListRowSelector: typeof import('./src/components/selector/ListRowSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/navigator/SearchBar.vue')['default']
    ThemeToggle: typeof import('./src/components/navigator/ThemeToggle.vue')['default']
    ToolBar: typeof import('./src/components/navigator/ToolBar.vue')['default']
    TreeSelector: typeof import('./src/components/selector/TreeSelector.vue')['default']
    VerticalLayout: typeof import('./src/components/layout/VerticalLayout.vue')['default']
  }
}
