/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    BaseChatList: typeof import('./src/components/chat/BaseChatList.vue')['default']
    BaseNavigator: typeof import('./src/components/navigator/BaseNavigator.vue')['default']
    BasePageLayout: typeof import('./src/components/layout/BasePageLayout.vue')['default']
    Navigator: typeof import('./src/components/navigator/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/navigator/SearchBar.vue')['default']
    ThemeToggle: typeof import('./src/components/navigator/ThemeToggle.vue')['default']
    ToolBar: typeof import('./src/components/navigator/ToolBar.vue')['default']
  }
}
